version: 0.2

phases:
  pre_build:
    commands:
      - echo "Downloading kubectl and configuring cluster access"
      - aws eks update-kubeconfig --name kube32newek --region ap-south-1 --role-arn arn:aws:iam::026894909295:role/CodeBuildServiceRole
  build:
    commands:
      - echo "Updating Kubernetes deployment with the latest image from ECR"
      - sed -i 's|CONTAINER_IMAGE_PLACEHOLDER|026894909295.dkr.ecr.ap-south-1.amazonaws.com/webapp-page:latest|' deployment.yaml
  post_build:
    commands:
      - echo "Applying updated Kubernetes deployment"
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

# Optional: Define output artifacts
artifacts:
  files:
    - kubernetes/deployment.yaml
    - kubernetes/service.yaml

