apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app-test
  template:
    metadata:
      labels:
        app: my-web-app-test
    spec:
      containers:
      - name: my-web-app-test
        image: 026894909295.dkr.ecr.ap-south-1.amazonaws.com/webapp-page:latest
        ports:
        - containerPort: 80
